// Visual self-review — the build agent's own eyes on its own work.
//
// audit.js is a deterministic linter (contrast, spacing, AI-tell fonts). This
// is the other half: it SCREENSHOTS your running pages and sends them to the
// design model (Grok, via the build's LLM_* credentials) for a human-style
// critique — hierarchy, balance, "does this look designed or generated" — and
// prints concrete improvements. It's the same visual review the studio runs on
// the deployed site, brought INTO the build loop where a fix is one edit away
// instead of a whole redeploy. A picture is worth a thousand tokens.
//
//   node scripts/design-review.js [baseURL]     default http://localhost:8080
//
// Output is one of:
//   SHIP                      — looks intentionally designed; nothing to do
//   POLISH  + up to 3 fixes   — apply them, then run this again to confirm
//
// Best-effort by design: if no vision model is configured or it can't be
// reached, it prints a note and exits 0 — audit.js remains the hard gate.
// Playwright is preinstalled globally with NODE_PATH preset, so this runs
// as-is. Do NOT edit this file.

const { chromium } = require('playwright');

const BASE = (process.argv[2] || 'http://localhost:8080').replace(/\/$/, '');
const KEY = process.env.LLM_API_KEY;
const LLM = (process.env.LLM_BASE_URL || '').replace(/\/$/, '');
const MODEL = process.env.LLM_MODEL;

const SYSTEM = `You are the design director doing a visual review of a website your studio is about to hand to a paying customer. You are looking at real screenshots of its pages.
Judge like a human looking at desktop AND mobile screens, not a linter:
- visual hierarchy, balance, alignment, spacing rhythm, and whether palette/type/layout feel intentional and specific to this business;
- whether the first two screenfuls communicate who/what/where, one primary action, and a real reason to trust or choose the business;
- whether the page is unnecessarily long, repetitive, dominated by a catalogue, or padded with generic cards/process/FAQ content;
- whether navigation, forms, footer and responsive reflow look complete rather than merely functional;
- image correctness: every labelled product/project image must visibly match its nearby label. Reject adjacent substitutions (a cookie labelled croissant), garbled or misspelled text, unwanted labels/logos, unsafe technical diagrams, unsupported standards/certification claims, and inconsistent image art direction. A raster logo with suspicious lettering is a visible defect.
Reply in EXACTLY one of these two forms:
SHIP
(nothing else — both viewport sizes look intentionally designed, conversion is clear, and every sampled image matches its labelled subject)
or:
POLISH
1. <one concrete, visually verifiable fix, phrased as an instruction to the builder, e.g. "The hero headline and the search card are both centred and the same weight — make the headline larger and left-align the section so it has a clear focal point.">
2. <next fix>
(3 issues maximum — prioritize wrong/malformed imagery, broken mobile composition and unclear conversion before cosmetic polish. Only things a paying customer would notice; no nitpicks, no code. Every issue must be visible in the screenshots.)`;

async function screenshots() {
  const browser = await chromium.launch();
  const shots = [], samples = [];
  try {
    const discover = await browser.newPage({ viewport: { width: 1280, height: 900 } });
    await discover.goto(BASE, { waitUntil: 'networkidle', timeout: 20000 });
    const hrefs = await discover.$$eval('a[href]', (as) => as.map((a) => a.getAttribute('href')));
    const routes = ['/', ...new Set(hrefs)]
      .filter((h, i, all) => all.indexOf(h) === i)
      .filter((h) => h && h.startsWith('/') && !/\.(css|js|png|jpe?g|svg|ico|webp|avif|gif)$/i.test(h))
      .filter((h) => !/^\/(static|logout|admin|app|login|signup)(\/|$)/.test(h))
      .slice(0, 4);

    // Individual image crops preserve enough detail for semantic/OCR review;
    // full-page screenshots alone can make a wrong product look plausible.
    const imgs = discover.locator('main img:visible');
    for (let i = 0; i < Math.min(await imgs.count(), 6); i++) {
      const img = imgs.nth(i);
      try {
        const meta = await img.evaluate((el) => {
          const near = el.closest('article, li, figure, section');
          return { alt: el.getAttribute('alt') || '', context: (near?.innerText || '').trim().replace(/\s+/g, ' ').slice(0, 180) };
        });
        samples.push({ label: `image sample ${i + 1}; nearby text: ${meta.context || '(none)'}; alt: ${meta.alt || '(empty)'}`, bytes: await img.screenshot({ type: 'jpeg', quality: 82 }) });
      } catch {}
    }
    await discover.close();

    for (const viewport of [{ name: 'desktop', width: 1280, height: 900 }, { name: 'mobile', width: 390, height: 844 }]) {
      const page = await browser.newPage({ viewport });
      for (const route of routes) {
        try {
          await page.goto(BASE + route, { waitUntil: 'networkidle', timeout: 20000 });
          shots.push({ label: `${route} — ${viewport.name} ${viewport.width}×${viewport.height}`, bytes: await page.screenshot({ fullPage: true, type: 'jpeg', quality: 74 }) });
        } catch {}
      }
      await page.close();
    }
  } finally {
    await browser.close();
  }
  return { shots, samples };
}

async function critique(review) {
  const parts = [{ type: 'text', text: 'Review these page screenshots and reply with SHIP, or POLISH and the fixes.' }];
  for (const shot of review.shots.slice(0, 8)) {
    parts.push({ type: 'text', text: shot.label });
    parts.push({ type: 'image_url', image_url: { url: 'data:image/jpeg;base64,' + shot.bytes.toString('base64') } });
  }
  for (const sample of review.samples.slice(0, 6)) {
    parts.push({ type: 'text', text: sample.label });
    parts.push({ type: 'image_url', image_url: { url: 'data:image/jpeg;base64,' + sample.bytes.toString('base64') } });
  }
  const body = { model: MODEL, max_tokens: 2000, messages: [
    { role: 'system', content: SYSTEM },
    { role: 'user', content: parts },
  ] };
  const resp = await fetch(LLM + '/chat/completions', {
    method: 'POST',
    headers: { 'content-type': 'application/json', authorization: 'Bearer ' + KEY },
    body: JSON.stringify(body),
  });
  const raw = await resp.text();
  let parsed;
  try { parsed = JSON.parse(raw); } catch { throw new Error('non-JSON response (status ' + resp.status + '): ' + raw.slice(0, 160)); }
  if (parsed.error) throw new Error(parsed.error.message || JSON.stringify(parsed.error));
  const msg = parsed.choices && parsed.choices[0] && parsed.choices[0].message && parsed.choices[0].message.content;
  if (!msg || !msg.trim()) throw new Error('empty response (status ' + resp.status + ')');
  return msg.trim();
}

async function main() {
  if (!KEY || !LLM || !MODEL) {
    console.log('design review: no vision model configured — rely on scripts/audit.js.');
    return;
  }
  let review;
  try { review = await screenshots(); } catch (e) {
    console.log('design review: could not screenshot the site (' + e.message + ') — is ./scripts/serve.sh running? Skipping.');
    return;
  }
  if (!review.shots.length) { console.log('design review: no pages captured — skipping.'); return; }
  let verdict;
  try { verdict = await critique(review); } catch (e) {
    console.log('design review: vision model unavailable (' + e.message + ') — rely on scripts/audit.js.');
    return;
  }
  console.log('\n=== visual design review — ' + review.shots.length + ' viewport/page shot(s) + ' + review.samples.length + ' image sample(s) ===\n');
  console.log(verdict + '\n');
  // Also persist the verdict so the orchestrator can surface it to the operator
  // (the agent sees stdout, but the build log only records the command, not its
  // output). Last run wins — that's the state at deploy time.
  try { require('fs').writeFileSync('/tmp/forge-design-review.txt', verdict); } catch {}
}

// Advisory: always exit 0 so a review hiccup never blocks a good build. The
// agent reads the printed feedback and decides what to fix.
main().catch((e) => { console.log('design review: ' + e.message + ' — skipping.'); }).finally(() => process.exit(0));
