// Visual self-review — the build agent's own eyes on its own work.
//
// audit.js is a deterministic linter (contrast, spacing, AI-tell fonts). This
// is the other half: it SCREENSHOTS your running pages and sends them to the
// design model (Grok, via the build's LLM_* credentials) for a human-style
// critique — hierarchy, balance, "does this look designed or generated" — and
// prints concrete improvements. It's the same visual review the studio runs on
// the deployed site, brought INTO the build loop where a fix is one edit away
// instead of a whole redeploy. A picture is worth a thousand tokens.
//
//   node scripts/design-review.js [baseURL]     default http://localhost:8080
//
// Output is one of:
//   SHIP                      — looks intentionally designed; nothing to do
//   POLISH  + up to 3 fixes   — apply them, then run this again to confirm
//
// Best-effort by design: if no vision model is configured or it can't be
// reached, it prints a note and exits 0 — audit.js remains the hard gate.
// Playwright is preinstalled globally with NODE_PATH preset, so this runs
// as-is. Do NOT edit this file.

const { chromium } = require('playwright');

const BASE = (process.argv[2] || 'http://localhost:8080').replace(/\/$/, '');
const KEY = process.env.LLM_API_KEY;
const LLM = (process.env.LLM_BASE_URL || '').replace(/\/$/, '');
const MODEL = process.env.LLM_MODEL;

const SYSTEM = `You are the design director doing a visual review of a website your studio is about to hand to a paying customer. You are looking at real screenshots of its pages.
Judge like a human looking at a screen, not a linter: visual hierarchy, balance and alignment, spacing rhythm, whether the palette and type feel intentional and specific to this business, and whether anything looks broken, cramped, flush against an edge, misaligned, unreadable, or like a generic AI-generated template.
Reply in EXACTLY one of these two forms:
SHIP
(nothing else — the site looks intentionally designed by a person)
or:
POLISH
1. <one concrete, visually verifiable fix, phrased as an instruction to the builder, e.g. "The hero headline and the search card are both centred and the same weight — make the headline larger and left-align the section so it has a clear focal point.">
2. <next fix>
(3 issues maximum — only things a paying customer would notice; no nitpicks, no code, no restating the brief. Every issue must be visible in the screenshots.)`;

async function screenshots() {
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  const shots = [];
  const shoot = async () => shots.push(await page.screenshot({ fullPage: true, type: 'jpeg', quality: 72 }));
  try {
    await page.goto(BASE, { waitUntil: 'networkidle', timeout: 20000 });
    await shoot();
    const hrefs = await page.$$eval('a[href]', (as) => as.map((a) => a.getAttribute('href')));
    const routes = [...new Set(hrefs)]
      .filter((h) => h && h.startsWith('/') && !/\.(css|js|png|jpe?g|svg|ico|webp|gif)$/i.test(h))
      .filter((h) => !/^\/(static|logout|admin)(\/|$)/.test(h))
      .slice(0, 3);
    for (const r of routes) {
      try {
        await page.goto(BASE + r, { waitUntil: 'networkidle', timeout: 20000 });
        await shoot();
      } catch {}
    }
  } finally {
    await browser.close();
  }
  return shots;
}

async function critique(shots) {
  const parts = [{ type: 'text', text: 'Review these page screenshots and reply with SHIP, or POLISH and the fixes.' }];
  for (const png of shots.slice(0, 4)) {
    parts.push({ type: 'image_url', image_url: { url: 'data:image/jpeg;base64,' + png.toString('base64') } });
  }
  const body = { model: MODEL, max_tokens: 1500, messages: [
    { role: 'system', content: SYSTEM },
    { role: 'user', content: parts },
  ] };
  const resp = await fetch(LLM + '/chat/completions', {
    method: 'POST',
    headers: { 'content-type': 'application/json', authorization: 'Bearer ' + KEY },
    body: JSON.stringify(body),
  });
  const raw = await resp.text();
  let parsed;
  try { parsed = JSON.parse(raw); } catch { throw new Error('non-JSON response (status ' + resp.status + '): ' + raw.slice(0, 160)); }
  if (parsed.error) throw new Error(parsed.error.message || JSON.stringify(parsed.error));
  const msg = parsed.choices && parsed.choices[0] && parsed.choices[0].message && parsed.choices[0].message.content;
  if (!msg || !msg.trim()) throw new Error('empty response (status ' + resp.status + ')');
  return msg.trim();
}

async function main() {
  if (!KEY || !LLM || !MODEL) {
    console.log('design review: no vision model configured — rely on scripts/audit.js.');
    return;
  }
  let shots;
  try { shots = await screenshots(); } catch (e) {
    console.log('design review: could not screenshot the site (' + e.message + ') — is ./scripts/serve.sh running? Skipping.');
    return;
  }
  if (!shots.length) { console.log('design review: no pages captured — skipping.'); return; }
  let verdict;
  try { verdict = await critique(shots); } catch (e) {
    console.log('design review: vision model unavailable (' + e.message + ') — rely on scripts/audit.js.');
    return;
  }
  console.log('\n=== visual design review — ' + shots.length + ' page(s), by the design model ===\n');
  console.log(verdict + '\n');
  // Also persist the verdict so the orchestrator can surface it to the operator
  // (the agent sees stdout, but the build log only records the command, not its
  // output). Last run wins — that's the state at deploy time.
  try { require('fs').writeFileSync('/tmp/forge-design-review.txt', verdict); } catch {}
}

// Advisory: always exit 0 so a review hiccup never blocks a good build. The
// agent reads the printed feedback and decides what to fix.
main().catch((e) => { console.log('design review: ' + e.message + ' — skipping.'); }).finally(() => process.exit(0));
